name: Java CI with JReleaser

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --no-daemon

      - name: Run tests
        if: github.event_name != 'release'
        run: ./gradlew test --stacktrace --no-daemon

      - name: Upload Test Results
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Install JReleaser
        if: github.event_name == 'release'
        run: |
          curl -Ls https://get.jreleaser.org | bash
          export PATH="$HOME/.jreleaser/bin:$PATH"

      - name: Configure GPG Key
        if: github.event_name == 'release'
        env:
          GPG_SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_SIGNING_KEY" | base64 --decode | gpg --batch --import

      - name: Release with JReleaser
        if: github.event_name == 'release'
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_SIGNING_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          JRELEASER_PROJECT_VERSION: ${{ github.event.release.tag_name }}
        run: |
          jreleaser release --debug
