name: Java CI with Gradle and Maven Central Upload

on:
  push:
    branches: [ fix-unnable-publish-issue ]
  pull_request:
    branches: [ fix-unnable-publish-issue ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        continue-on-error: true

      - name: Run tests
        if: github.event_name != 'release'
        run: ./gradlew test

      - name: Upload Test results
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports

      - name: Debug Environment Variables
        run: |
          echo "MAVEN_USERNAME length: ${#${{ secrets.OSSRH_USERNAME }}}"
          echo "SAMPLE_SECRET: ${{ secrets.SAMPLE_SECRET }}"
          echo "MAVEN_PASSWORD: [REDACTED]"
          echo "GPG_SIGNING_KEY: [REDACTED]"
          echo "GPG_SIGNING_PASSWORD: [REDACTED]"

      - name: Publish to Maven Central
        run: |
          ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
